// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChessService_SendInvite_FullMethodName    = "/chessservice.ChessService/SendInvite"
	ChessService_LookupByEmail_FullMethodName = "/chessservice.ChessService/LookupByEmail"
	ChessService_SendWelcome_FullMethodName   = "/chessservice.ChessService/SendWelcome"
)

// ChessServiceClient is the client API for ChessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChessServiceClient interface {
	SendInvite(ctx context.Context, in *SendInviteRequest, opts ...grpc.CallOption) (*SendInviteResponse, error)
	LookupByEmail(ctx context.Context, in *LookupByEmailRequest, opts ...grpc.CallOption) (*LookupByEmailResponse, error)
	SendWelcome(ctx context.Context, in *SendWelcomeRequest, opts ...grpc.CallOption) (*SendWelcomeResponse, error)
}

type chessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChessServiceClient(cc grpc.ClientConnInterface) ChessServiceClient {
	return &chessServiceClient{cc}
}

func (c *chessServiceClient) SendInvite(ctx context.Context, in *SendInviteRequest, opts ...grpc.CallOption) (*SendInviteResponse, error) {
	out := new(SendInviteResponse)
	err := c.cc.Invoke(ctx, ChessService_SendInvite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chessServiceClient) LookupByEmail(ctx context.Context, in *LookupByEmailRequest, opts ...grpc.CallOption) (*LookupByEmailResponse, error) {
	out := new(LookupByEmailResponse)
	err := c.cc.Invoke(ctx, ChessService_LookupByEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chessServiceClient) SendWelcome(ctx context.Context, in *SendWelcomeRequest, opts ...grpc.CallOption) (*SendWelcomeResponse, error) {
	out := new(SendWelcomeResponse)
	err := c.cc.Invoke(ctx, ChessService_SendWelcome_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChessServiceServer is the server API for ChessService service.
// All implementations should embed UnimplementedChessServiceServer
// for forward compatibility
type ChessServiceServer interface {
	SendInvite(context.Context, *SendInviteRequest) (*SendInviteResponse, error)
	LookupByEmail(context.Context, *LookupByEmailRequest) (*LookupByEmailResponse, error)
	SendWelcome(context.Context, *SendWelcomeRequest) (*SendWelcomeResponse, error)
}

// UnimplementedChessServiceServer should be embedded to have forward compatible implementations.
type UnimplementedChessServiceServer struct {
}

func (UnimplementedChessServiceServer) SendInvite(context.Context, *SendInviteRequest) (*SendInviteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInvite not implemented")
}
func (UnimplementedChessServiceServer) LookupByEmail(context.Context, *LookupByEmailRequest) (*LookupByEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupByEmail not implemented")
}
func (UnimplementedChessServiceServer) SendWelcome(context.Context, *SendWelcomeRequest) (*SendWelcomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWelcome not implemented")
}

// UnsafeChessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChessServiceServer will
// result in compilation errors.
type UnsafeChessServiceServer interface {
	mustEmbedUnimplementedChessServiceServer()
}

func RegisterChessServiceServer(s grpc.ServiceRegistrar, srv ChessServiceServer) {
	s.RegisterService(&ChessService_ServiceDesc, srv)
}

func _ChessService_SendInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChessServiceServer).SendInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChessService_SendInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChessServiceServer).SendInvite(ctx, req.(*SendInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChessService_LookupByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChessServiceServer).LookupByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChessService_LookupByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChessServiceServer).LookupByEmail(ctx, req.(*LookupByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChessService_SendWelcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWelcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChessServiceServer).SendWelcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChessService_SendWelcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChessServiceServer).SendWelcome(ctx, req.(*SendWelcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChessService_ServiceDesc is the grpc.ServiceDesc for ChessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chessservice.ChessService",
	HandlerType: (*ChessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendInvite",
			Handler:    _ChessService_SendInvite_Handler,
		},
		{
			MethodName: "LookupByEmail",
			Handler:    _ChessService_LookupByEmail_Handler,
		},
		{
			MethodName: "SendWelcome",
			Handler:    _ChessService_SendWelcome_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
